// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyS7lxiHtEZXyPgIaIw50NhO1rXw3gro0',
    appId: '1:731902350583:web:76379401c95928a4212ff2',
    messagingSenderId: '731902350583',
    projectId: 'n-valid',
    authDomain: 'n-valid.firebaseapp.com',
    storageBucket: 'n-valid.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1mS0VaGjgI0xZkZVVqZExbePw56eEcd0',
    appId: '1:731902350583:android:098d3157228eb8f9212ff2',
    messagingSenderId: '731902350583',
    projectId: 'n-valid',
    storageBucket: 'n-valid.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXrZvhvSCynJor7cIeNnA5ZQt0OHBdaVk',
    appId: '1:731902350583:ios:b6383ea6b2dfc1ee212ff2',
    messagingSenderId: '731902350583',
    projectId: 'n-valid',
    storageBucket: 'n-valid.appspot.com',
    iosBundleId: 'com.example.nValid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXrZvhvSCynJor7cIeNnA5ZQt0OHBdaVk',
    appId: '1:731902350583:ios:b6383ea6b2dfc1ee212ff2',
    messagingSenderId: '731902350583',
    projectId: 'n-valid',
    storageBucket: 'n-valid.appspot.com',
    iosBundleId: 'com.example.nValid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyS7lxiHtEZXyPgIaIw50NhO1rXw3gro0',
    appId: '1:731902350583:web:334b8abedafdefef212ff2',
    messagingSenderId: '731902350583',
    projectId: 'n-valid',
    authDomain: 'n-valid.firebaseapp.com',
    storageBucket: 'n-valid.appspot.com',
  );

}